# User config
author: "Jeff Butler"
tagline: "Interests and Projects"
description: "I am a technologist who aims to make meaningful contributions to socially impactful projects. My passion for analytical problem solving and innovation has steered me into a diverse array of international career opportunities, spanning industries from finance and professional sports, to supply chain."
keywords: "Pineapple, Pineapple Pizza, Pineapple House"
email: "pineapple@example.com"
linkedin: "https://www.linkedin.com/jeffreyrbutler"
github: "https://github.com/"

# Site config
baseurl: "/JB2013"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
